sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.070.1
 - dmd-2.069.2
 - dmd-2.068.2
 - dmd-2.067.1
 - ldc-1.0.0-alpha1
 - ldc-0.17.0
 - ldc-0.16.0
 - gdc-5.2.0

matrix:
  allow_failures:
   - d: gdc-5.2.0
   - d: dmd-2.067.1

env:
  matrix:
    - ARCH=x86
    - ARCH=x86_64

# enable 32 bit compilation on 64 bit worker
addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH