sudo: false

os:
 - linux

language: d

d:
 - dmd-2.071.2
 - dmd-2.070.2
 - dmd-2.069.2
 - dmd-2.068.2
 - ldc-1.1.0-beta3
 - ldc-1.0.0

matrix:
  allow_failures:
   - d: ldc-1.0.0

env:
  matrix:
    - ARCH=x86
    - ARCH=x86_64

# enable 32 bit compilation on 64 bit worker
addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH