sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.070.0
 - dmd-2.069.2
 - dmd-2.068.2
 - dmd-2.067.1

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

# enable 32 bit compilation on 64 bit worker
addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH