sudo: false

os:
 - linux

language: d

d:
 - dmd-2.096.0
 - dmd-2.095.1
 - dmd-2.094.2
 - dmd-2.093.1
 - dmd-2.092.1
 - dmd-2.091.1
 - dmd-2.090.1
 - dmd-2.089.1
 - dmd-2.088.1
 - dmd-2.087.1
 - dmd-2.086.1
 - dmd-2.085.1
 - dmd-2.084.1
 - dmd-2.083.1
 - dmd-2.082.1
 - ldc-1.25.1
 - ldc-1.24.0
 - ldc-1.23.0
 - ldc-1.22.0
 - ldc-1.21.0
 - ldc-1.20.1
 - ldc-1.19.0
 - ldc-1.18.0
 - ldc-1.17.0
 - ldc-1.16.0
 - ldc-1.15.0
 - ldc-1.14.0
 - ldc-1.13.0
 - ldc-1.12.0
 - ldc-1.11.0

matrix:
  allow_failures:
    - d:

env:
  matrix:
    - ARCH=x86
    - ARCH=x86_64

# enable 32 bit compilation on 64 bit worker
addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH
