sudo: false

os:
 - linux

language: d

d:
 - dmd-2.080.1
 - dmd-2.079.1
 - dmd-2.078.3
 - dmd-2.077.1
 - dmd-2.076.1
 - dmd-2.075.1
 - dmd-2.074.1
 - dmd-2.073.2
 - dmd-2.072.2
 - dmd-2.071.2
 - dmd-2.070.2
 - dmd-2.069.2
 - dmd-2.068.2
 - ldc-1.9.0
 - ldc-1.8.0
 - ldc-1.7.0
 - ldc-1.6.0
 - ldc-1.5.0
 - ldc-1.4.0
 - ldc-1.3.0
 - ldc-1.2.0
 - ldc-1.1.0
 - ldc-1.0.0

matrix:
  allow_failures:
    - d:

env:
  matrix:
    - ARCH=x86
    - ARCH=x86_64

# enable 32 bit compilation on 64 bit worker
addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH