sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.071.0
 - dmd-2.070.2
 - dmd-2.069.2
 - dmd-2.068.2
 - ldc-1.0.0-alpha1
 - ldc-1.0.0
 - ldc-0.17.0

matrix:
  allow_failures:
   - ldc-1.0.0

env:
  matrix:
    - ARCH=x86
    - ARCH=x86_64

# enable 32 bit compilation on 64 bit worker
addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH